### ISSUE TITLE
Gemfile?

### ISSUE THREAD

**Issue by naltun** [journaltxt/journaltxt#1]
I noticed you're using `logutils` and `props`. Are you going to add a Gemfile?

**Comment by geraldb** [comment]
@naltun  Thanks for following along. Still working on the first version for later this week. The current version published on rubygems is a "dummy".

**Comment by naltun** [comment]
Awesome man, looking forward to what's to come. :+1:
Feel free to close this issue.

**Comment by geraldb** [comment]
@naltun FYI: The first version (1.0.1) of journaltxt is now uploaded to rubygems - plus added some docu to the README. Have a great weekend. Cheers. PS: As of 1.0.1 there are no "3rd party dependencies" e.g. no logutils and props for now.
