### ISSUE TITLE
I cannot get this to work at all.

### ISSUE THREAD

**Issue by Skippy-T-Wonderlizard** [journaltxt/journaltxt#2]
Tried entering "journaltext," "jo," etc.
![Screen Shot 2021-10-08 at 1 00 07 PM](https://user-images.githubusercontent.com/89996450/136602469-86392895-665c-4f5b-96ed-b1c827bbda1f.jpg)
.

**Comment by geraldb** [comment]
If you do NOT pass along a filename than the default is journal.txt.

Sorry - the error tells you that no such file journal.txt.     Create a journal.txt file and try again. 

For support questions (as stated on the readme) please use the forum <http://groups.google.com/group/wwwmake> Thanks.
